version: '3'
services:
  workspace:
    build: ./docker/workspace/
    container_name: dishlist_workspace
    volumes:
      - ".:/var/www"
      - "${ANDROID_HOME}/platforms:/usr/local/android-sdk-linux/platforms"
      - "${ANDROID_HOME}/build-tools:/usr/local/android-sdk-linux/build-tools"
    tty: true
    expose:
      - "80"
    ports:
      - "80:8080"
